/* eslint-disable max-lines-per-function */

import { Image, Platform } from 'react-native';

import { colors } from '@/ui';

const androidDrawableResPath = `file:///android_res/drawable`;
const getAndroidReleaseImageURI = (sourceURI: string) =>
  `${androidDrawableResPath}/${sourceURI}`;
const isAndroidRelease = Platform.OS === 'android' && !__DEV__;

const medicalFrameImg = Image.resolveAssetSource(
  require('assets/medical_frame.png'),
);
const iconAsset = Image.resolveAssetSource(
  require('assets/icon_transparent.png'),
);

const medicalImageUrl = isAndroidRelease
  ? getAndroidReleaseImageURI(medicalFrameImg.uri)
  : medicalFrameImg.uri;
const medicalImageUrlV2 = isAndroidRelease
  ? 'file:///android_asset/medical_frame.png'
  : medicalFrameImg.uri;
const medicalImageUrlV3 = isAndroidRelease
  ? 'file:///android_res/drawable/medical_frame.png'
  : medicalFrameImg.uri;
const logo = isAndroidRelease
  ? 'file:///android_res/drawable/icon_transparent.png'
  : iconAsset.uri;
interface IGenerateScanReportPdf {
  createdAt: string;
  interpretation: string;
  promptMessage: string;
  generatedAt: string;
  logoBase64: string;
  medicalFrameBase64: string;
}

export const generateScanReportPdf = ({
  createdAt,
  interpretation,
  promptMessage,
  generatedAt,
  logoBase64,
  medicalFrameBase64,
}: IGenerateScanReportPdf) => {
  // const logo = `data:image/jpeg;base64,${logoBase64}`;
  // const medicalFrame = `data:image/jpeg;base64,${medicalFrameBase64}`;

  return `
   <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Analysis Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
        }
        .container {
            background: white;
            padding: 40px;
            border:1px solid ${colors.lightGray};
            border-radius:30px;
          
        }
        .header {
            text-align: center;
            display:flex;
            flex-direction:row;
            justify-content:center;
          align-items:center;
            gap:10px;
        }
        .branding-text{
        display:flex;
        flex-direction:column;
        margin-top:-20px;
        }

        .background-overlay{
        position:absolute;
        left:25%;
        opacity:0.7;

        }

        .logo {
            width: 70px;
            height: 70px;
        }
        h1 {
            font-size: 22px;
            margin: 10px 0;
        }
        .info {
            display: flex;
            justify-content: space-between;
            font-size: 14px;
            color: #666;
            margin-bottom: 20px;
        }
        .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #7982FD;
            margin-bottom: 5px;
        }
        .content {
            font-size: 14px;
            color: #333;
            line-height: 1.5;
        }
        .footer {
            font-size: 12px;
            color: #999;
            margin-top: 20px;
            border-top: 1px solid #eee;
            padding-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="container">
        <!-- Header -->
        <div class="header">
            <img src=${logo} alt="X-Ray Analyzer Logo" class="logo">
            <div class="branding-text">
            <p style="font-size:40px; line-height:0px; font-weight:800">X-Ray</p>
            <p style="letter-spacing:4px; line-height:0px; margin-top:3px; font-size:25">ANALYZER</p>
             </div>
        </div>
      <p style="text-align: center; font-size:24px; font-weight:700">Document Analysis Report</p>


        <!-- Info -->
        <div class="info">
            <div><strong>Created At:</strong> ${generatedAt}</div>
        </div>

        <!-- Analysis Prompt -->
        <div>
            <p class="section-title">Analysis Prompt</p>
            <p class="content">${promptMessage || '-'}</p>
        </div>

        <!-- AI Interpretation -->
        <div style="position:relative">
            <img class="background-overlay" src=${medicalImageUrlV3} />
            <p class="section-title">AI Interpretation</p>
            <p class="content">
              ${interpretation}
                </p>

        </div>

        <!-- Footer -->
         <footer style="
          text-align: center;
          padding: 20px;
          color: #64748b;
          font-size: 12px;
          border-top: 1px solid #e2e8f0;
          margin-top: 100px;
          
        ">
          <p style="margin: 0;">Generated by X-Ray Analyzer • ${createdAt}</p>
          <p style="margin: 0;">The AI-generated results from X-ray Analyzer are intended for informational purposes only and should not be used as a substitute for professional medical advice. Always seek guidance from a qualified healthcare professional for diagnosis and treatment.
</p>

        </footer>

    </div>
</body>
</html>
  `;
};
